
version: '3'

services:
  db:
    image: postgres
    restart: always
    container_name: postgresql
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: server
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379